version: '3.8'

services:
  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker_network
    
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - docker_network

networks:
  docker_network:
    name: docker_network
    