version: '3.8'

services:
  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker_network
    
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - docker_network
    
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    depends_on:
#      - mysql
#    restart: unless-stopped
#    ports:
#      - '8080:80'
#    environment:
#      PMA_HOST: mysql
#      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
#    networks:
#      - docker_network

networks:
  docker_network:
    name: docker_network
    