version: '3.8'

services:
  site:
    container_name: $NAME
    image: wordpress:latest
    restart: always
    env_file: .env
    environment:
      VIRTUAL_HOST: $ALIASES
      WORDPRESS_DB_HOST: $MYSQL_HOST
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_NAME
      WORDPRESS_CONFIG_EXTRA: |
        require_once(__DIR__ .'/../vendor/autoload.php');
        define('DISALLOW_FILE_EDIT', true);
        define('AUTOMATIC_UPDATER_DISABLED', true);
    volumes:
      - ./html/wp-content:/var/www/html/wp-content
      - ./vendor:/var/www/vendor
    networks:
      - docker_network
        
  composer:
    image: composer:latest
    depends_on:
      - site
    restart: 'no'
    command: install
    working_dir: /var/www
    volumes:
      - ./html/wp-content:/var/www/html/wp-content
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock

networks:
  docker_network:
    name: docker_network